name: Trigger spring-aws-lambda-init Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in spring-aws-lambda-init repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: taeyun1215/lambda-trigger-pipeline
          event-type: deploy-trigger